import { useState } from "react";
import { Button, Modal, Separator, toast } from "@heroui/react";
import { Copy, FileText, Image as ImageIcon, Share2 } from "lucide-react";
import type { Business, Order } from "../types";
import {
  formatDate,
  formatINR,
  lineTotal,
  orderNumber,
  orderTotal,
} from "../lib/format";

function OrderDocument({
  order,
  business,
}: {
  order: Order;
  business: Business | null;
}) {
  return (
    <div className="rounded-lg border border-separator bg-white p-4 text-left text-sm text-neutral-900 shadow-sm">
      <div className="border-b border-neutral-200 pb-3">
        <p className="text-base font-bold">{business?.name ?? "Order Tracker"}</p>
        {business?.address ? (
          <p className="whitespace-pre-line text-xs text-neutral-500">
            {business.address}
          </p>
        ) : null}
        {business?.phone ? (
          <p className="text-xs text-neutral-500">Phone: {business.phone}</p>
        ) : null}
        {business?.pan ? (
          <p className="text-xs text-neutral-500">PAN: {business.pan}</p>
        ) : null}
        {business?.gst ? (
          <p className="text-xs text-neutral-500">GST: {business.gst}</p>
        ) : null}
      </div>

      <div className="flex items-baseline justify-between py-2">
        <span className="font-mono font-semibold">{orderNumber(order.number)}</span>
        <span className="text-xs text-neutral-500">{formatDate(order.createdAt)}</span>
      </div>
      <p className="font-medium">{order.customerSnapshot.name}</p>
      {order.customerSnapshot.phone ? (
        <p className="text-xs text-neutral-500">{order.customerSnapshot.phone}</p>
      ) : null}
      {order.customerSnapshot.address ? (
        <p className="whitespace-pre-line text-xs text-neutral-500">
          {order.customerSnapshot.address}
        </p>
      ) : null}

      <table className="mt-3 w-full text-xs">
        <thead>
          <tr className="border-b border-neutral-200 text-left text-neutral-500">
            <th className="py-1 font-medium">Item</th>
            <th className="py-1 text-right font-medium">Qty</th>
            {order.priced ? (
              <>
                <th className="py-1 text-right font-medium">Rate</th>
                <th className="py-1 text-right font-medium">Total</th>
              </>
            ) : null}
          </tr>
        </thead>
        <tbody>
          {order.lines.map((line) => (
            <tr key={line.id} className="border-b border-neutral-100">
              <td className="py-1.5">{line.itemName}</td>
              <td className="py-1.5 text-right whitespace-nowrap">
                {line.qty} {line.unit}
              </td>
              {order.priced ? (
                <>
                  <td className="py-1.5 text-right">
                    {formatINR(line.unitPrice ?? 0)}
                  </td>
                  <td className="py-1.5 text-right">{formatINR(lineTotal(line))}</td>
                </>
              ) : null}
            </tr>
          ))}
        </tbody>
        {order.priced ? (
          <tfoot>
            <tr>
              <td className="pt-2 font-semibold" colSpan={3}>
                Total
              </td>
              <td className="pt-2 text-right font-semibold">
                {formatINR(orderTotal(order))}
              </td>
            </tr>
          </tfoot>
        ) : null}
      </table>

      {order.notes ? (
        <p className="mt-3 rounded bg-neutral-50 p-2 text-xs text-neutral-600">
          Note: {order.notes}
        </p>
      ) : null}

      <p className="mt-3 text-center text-[10px] text-neutral-400">
        Generated by Order Tracker
      </p>
    </div>
  );
}

function buildShareText(order: Order, business: Business | null): string {
  const lines = order.lines
    .map(
      (l) =>
        `• ${l.itemName} — ${l.qty} ${l.unit}` +
        (order.priced && l.unitPrice != null ? ` @ ${formatINR(l.unitPrice)}` : ""),
    )
    .join("\n");
  const total = order.priced ? `\nTotal: ${formatINR(orderTotal(order))}` : "";
  return `${business?.name ?? "Order Tracker"} — Order ${orderNumber(order.number)}\n${order.customerSnapshot.name} · ${formatDate(order.createdAt)}\n\n${lines}${total}${order.notes ? `\n\nNote: ${order.notes}` : ""}`;
}

export function ShareSheet({
  order,
  business,
  isOpen,
  onOpenChange,
}: {
  order: Order;
  business: Business | null;
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const [format, setFormat] = useState<"pdf" | "image" | null>(null);

  const handleOpenChange = (open: boolean) => {
    if (!open) setFormat(null);
    onOpenChange(open);
  };

  const share = async () => {
    const text = buildShareText(order, business);
    try {
      if (navigator.share) {
        await navigator.share({ title: `Order ${orderNumber(order.number)}`, text });
      } else {
        await navigator.clipboard.writeText(text);
        toast.info("Share sheet not available here — order copied to clipboard.");
      }
      handleOpenChange(false);
    } catch {
      // user dismissed the share sheet
    }
  };

  const copyPhone = async () => {
    try {
      await navigator.clipboard.writeText(order.customerSnapshot.phone);
      toast.success("Phone number copied");
    } catch {
      toast.danger("Could not copy phone number");
    }
  };

  return (
    <Modal isOpen={isOpen} onOpenChange={handleOpenChange}>
      <Modal.Backdrop>
        <Modal.Container placement="bottom" scroll="inside">
          <Modal.Dialog>
            <Modal.Header>
              <Modal.Heading>
                {format === null
                  ? "Share order"
                  : format === "pdf"
                    ? "PDF preview"
                    : "Image preview"}
              </Modal.Heading>
              <Modal.CloseTrigger />
            </Modal.Header>
            <Modal.Body>
              {format === null ? (
                <div className="flex flex-col gap-3 pb-2">
                  <Button
                    fullWidth
                    size="lg"
                    variant="secondary"
                    onPress={() => setFormat("pdf")}
                  >
                    <FileText aria-hidden className="size-5" />
                    Share as PDF
                  </Button>
                  <Button
                    fullWidth
                    size="lg"
                    variant="secondary"
                    onPress={() => setFormat("image")}
                  >
                    <ImageIcon aria-hidden className="size-5" />
                    Share as image
                  </Button>
                  {order.customerSnapshot.phone ? (
                    <>
                      <Separator />
                      <button
                        type="button"
                        className="flex min-h-11 items-center justify-center gap-2 text-sm text-muted"
                        onClick={copyPhone}
                      >
                        <Copy aria-hidden className="size-4" />
                        {order.customerSnapshot.name}: {order.customerSnapshot.phone}
                      </button>
                    </>
                  ) : null}
                </div>
              ) : (
                <div className="flex flex-col gap-4 pb-2">
                  <OrderDocument business={business} order={order} />
                  <Button fullWidth size="lg" onPress={share}>
                    <Share2 aria-hidden className="size-5" />
                    Share via WhatsApp
                  </Button>
                  <p className="text-center text-xs text-muted">
                    Opens your phone's share sheet — pick WhatsApp and the
                    customer's chat.
                  </p>
                </div>
              )}
            </Modal.Body>
          </Modal.Dialog>
        </Modal.Container>
      </Modal.Backdrop>
    </Modal>
  );
}
